-- ============================================================
-- KLOAK & DAGGURRS V5 — SUPABASE DATABASE
-- Run this entire file once in Supabase -> SQL Editor.
-- ============================================================

create extension if not exists pgcrypto;


-- ---------- Accounts / existing-project compatibility ----------
-- If public.profiles already exists from an older Supabase starter,
-- CREATE TABLE IF NOT EXISTS will not add new V5 columns. Create the
-- minimal table if necessary, then migrate the existing one in place.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade
);

alter table public.profiles
  add column if not exists created_at timestamptz default now(),
  add column if not exists email text,
  add column if not exists display_name text default '',
  add column if not exists role text default 'player',
  add column if not exists active boolean default true;

-- Normalize any null/blank legacy values before adding constraints.
update public.profiles
set
  created_at = coalesce(created_at, now()),
  display_name = coalesce(display_name, ''),
  role = coalesce(nullif(role,''), 'player'),
  active = coalesce(active, true);

-- Backfill email and display name from Supabase Auth for existing accounts.
update public.profiles p
set
  email = coalesce(nullif(p.email,''), u.email),
  display_name = case
    when coalesce(p.display_name,'') = '' then
      coalesce(
        nullif(u.raw_user_meta_data->>'display_name',''),
        nullif(u.raw_user_meta_data->>'full_name',''),
        split_part(coalesce(u.email,''),'@',1)
      )
    else p.display_name
  end,
  created_at = coalesce(p.created_at, u.created_at, now())
from auth.users u
where p.id = u.id;

-- Add the V5 role check safely on an existing table.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.profiles'::regclass
      and conname = 'profiles_role_check'
  ) then
    alter table public.profiles
      add constraint profiles_role_check
      check (role in ('player','admin','owner'));
  end if;
end $$;

alter table public.profiles
  alter column created_at set default now(),
  alter column display_name set default '',
  alter column role set default 'player',
  alter column active set default true;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles(id,email,display_name,created_at,role,active)
  values (
    new.id,
    new.email,
    coalesce(
      nullif(new.raw_user_meta_data->>'display_name',''),
      nullif(new.raw_user_meta_data->>'full_name',''),
      split_part(coalesce(new.email,''),'@',1)
    ),
    coalesce(new.created_at, now()),
    'player',
    true
  )
  on conflict (id) do update
  set
    email = coalesce(excluded.email, public.profiles.email),
    display_name = case
      when coalesce(public.profiles.display_name,'') = ''
        then excluded.display_name
      else public.profiles.display_name
    end;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Backfill profiles for Auth users that do not yet have a public profile.
insert into public.profiles(id,email,display_name,created_at,role,active)
select
  id,
  email,
  coalesce(
    nullif(raw_user_meta_data->>'display_name',''),
    nullif(raw_user_meta_data->>'full_name',''),
    split_part(coalesce(email,''),'@',1)
  ),
  coalesce(created_at,now()),
  'player',
  true
from auth.users
on conflict(id) do nothing;

-- ---------- Authorization helper ----------
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and active = true
      and role in ('owner','admin')
  );
$$;
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- ---------- Game content ----------
create table if not exists public.factions (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  rune text not null default '◇',
  tagline text not null default '',
  lore text not null default '',
  doctrine text not null default '',
  accent text not null default '#7d43ff',
  image_url text,
  revealed boolean not null default false,
  reveal_at timestamptz,
  sort_order integer not null default 100
);

create table if not exists public.cards (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  card_number integer not null default 0,
  name text not null,
  faction_id bigint references public.factions(id) on delete set null,
  rarity text not null default 'Common',
  card_type text not null default 'Action',
  ability text not null default '',
  lore text not null default '',
  image_url text,
  revealed boolean not null default false,
  reveal_at timestamptz,
  sort_order integer not null default 100
);

create table if not exists public.whispers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  published_at date not null default current_date,
  title text not null,
  body text not null,
  classified boolean not null default false,
  image_url text,
  reveal_at timestamptz
);
create unique index if not exists whispers_title_date_uq on public.whispers(title,published_at);

create table if not exists public.vault_entries (
  id bigint generated by default as identity primary key,
  code text unique not null,
  title text not null,
  teaser text not null default '',
  body text not null default '',
  status text not null default 'locked' check (status in ('locked','open')),
  reveal_at timestamptz,
  access_code text,
  image_url text
);

create table if not exists public.vault_unlocks (
  user_id uuid not null references auth.users(id) on delete cascade,
  vault_entry_id bigint not null references public.vault_entries(id) on delete cascade,
  unlocked_at timestamptz not null default now(),
  primary key(user_id,vault_entry_id)
);

-- ---------- Player collections ----------
create table if not exists public.collections (
  user_id uuid not null references auth.users(id) on delete cascade,
  card_id bigint not null references public.cards(id) on delete cascade,
  quantity integer not null default 1 check (quantity between 1 and 99),
  updated_at timestamptz not null default now(),
  primary key(user_id,card_id)
);

-- ---------- Forge ----------
create table if not exists public.forge_orders (
  id uuid primary key default gen_random_uuid(),
  order_code text unique not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  customer_name text not null,
  email text not null,
  phone text,
  print_type text,
  quantity integer not null default 1 check (quantity > 0),
  deadline date,
  source_link text,
  colors text,
  notes text,
  status text not null default 'new'
    check (status in ('new','quoted','approved','printing','quality_check','ready','completed','cancelled')),
  customer_update text not null default ''
);

create table if not exists public.forge_order_updates (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.forge_orders(id) on delete cascade,
  created_at timestamptz not null default now(),
  status text not null,
  message text not null default ''
);

-- ---------- Reviews / contacts / subscribers ----------
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid references auth.users(id) on delete set null,
  name text not null,
  rating integer not null check (rating between 1 and 5),
  body text not null,
  approved boolean not null default false
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid references auth.users(id) on delete set null,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  status text not null default 'new' check (status in ('new','read','closed'))
);

create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  email text unique not null,
  active boolean not null default true
);

create table if not exists public.site_settings (
  key text primary key,
  value text not null default ''
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  detail text not null default ''
);

-- ---------- Media metadata ----------
create table if not exists public.media (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  owner_id uuid references auth.users(id) on delete set null,
  title text not null default '',
  alt_text text not null default '',
  category text not null default 'general',
  storage_path text unique not null,
  public boolean not null default true
);

-- ============================================================
-- RLS
-- ============================================================
alter table public.profiles enable row level security;
alter table public.factions enable row level security;
alter table public.cards enable row level security;
alter table public.whispers enable row level security;
alter table public.vault_entries enable row level security;
alter table public.vault_unlocks enable row level security;
alter table public.collections enable row level security;
alter table public.forge_orders enable row level security;
alter table public.forge_order_updates enable row level security;
alter table public.reviews enable row level security;
alter table public.contacts enable row level security;
alter table public.subscribers enable row level security;
alter table public.site_settings enable row level security;
alter table public.audit_log enable row level security;
alter table public.media enable row level security;

-- Remove broad grants first.
revoke all on table public.profiles, public.factions, public.cards, public.whispers,
  public.vault_entries, public.vault_unlocks, public.collections, public.forge_orders,
  public.forge_order_updates, public.reviews, public.contacts, public.subscribers,
  public.site_settings, public.audit_log, public.media
from anon, authenticated;

-- Accounts
grant select on public.profiles to authenticated;
grant update(display_name) on public.profiles to authenticated;

drop policy if exists "profile read own or admin" on public.profiles;
create policy "profile read own or admin"
on public.profiles for select to authenticated
using ((select auth.uid()) = id or public.is_admin());

drop policy if exists "profile update own" on public.profiles;
create policy "profile update own"
on public.profiles for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

-- Owner/admin content access
grant select,insert,update,delete on public.factions, public.cards, public.whispers,
  public.vault_entries, public.site_settings, public.media to authenticated;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='factions' and policyname='admins manage factions') then
    create policy "admins manage factions" on public.factions for all to authenticated using (public.is_admin()) with check (public.is_admin());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='cards' and policyname='admins manage cards') then
    create policy "admins manage cards" on public.cards for all to authenticated using (public.is_admin()) with check (public.is_admin());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='whispers' and policyname='admins manage whispers') then
    create policy "admins manage whispers" on public.whispers for all to authenticated using (public.is_admin()) with check (public.is_admin());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='vault_entries' and policyname='admins manage vault') then
    create policy "admins manage vault" on public.vault_entries for all to authenticated using (public.is_admin()) with check (public.is_admin());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='site_settings' and policyname='admins manage settings') then
    create policy "admins manage settings" on public.site_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='media' and policyname='admins manage media') then
    create policy "admins manage media" on public.media for all to authenticated using (public.is_admin()) with check (public.is_admin());
  end if;
end $$;

-- Collections
grant select,insert,update,delete on public.collections to authenticated;

drop policy if exists "players read own collection" on public.collections;
create policy "players read own collection"
on public.collections for select to authenticated
using ((select auth.uid()) = user_id or public.is_admin());

drop policy if exists "players insert own collection" on public.collections;
create policy "players insert own collection"
on public.collections for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "players update own collection" on public.collections;
create policy "players update own collection"
on public.collections for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "players delete own collection" on public.collections;
create policy "players delete own collection"
on public.collections for delete to authenticated
using ((select auth.uid()) = user_id);

-- Vault unlocks
grant select,insert on public.vault_unlocks to authenticated;

drop policy if exists "players read own vault unlocks" on public.vault_unlocks;
create policy "players read own vault unlocks"
on public.vault_unlocks for select to authenticated
using ((select auth.uid()) = user_id or public.is_admin());

drop policy if exists "players insert own vault unlocks" on public.vault_unlocks;
create policy "players insert own vault unlocks"
on public.vault_unlocks for insert to authenticated
with check ((select auth.uid()) = user_id);

-- Forge
grant select,insert on public.forge_orders to authenticated;
grant update on public.forge_orders to authenticated;
grant select on public.forge_order_updates to authenticated;
grant insert on public.forge_order_updates to authenticated;

drop policy if exists "customers create own forge order" on public.forge_orders;
create policy "customers create own forge order"
on public.forge_orders for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "customers read own forge orders" on public.forge_orders;
create policy "customers read own forge orders"
on public.forge_orders for select to authenticated
using ((select auth.uid()) = user_id or public.is_admin());

drop policy if exists "admins update forge orders" on public.forge_orders;
create policy "admins update forge orders"
on public.forge_orders for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "customers read own order updates" on public.forge_order_updates;
create policy "customers read own order updates"
on public.forge_order_updates for select to authenticated
using (
  public.is_admin()
  or exists (
    select 1 from public.forge_orders o
    where o.id = order_id and o.user_id = (select auth.uid())
  )
);

drop policy if exists "admins create order updates" on public.forge_order_updates;
create policy "admins create order updates"
on public.forge_order_updates for insert to authenticated
with check (public.is_admin());

-- Reviews
grant select,insert on public.reviews to anon, authenticated;
grant update,delete on public.reviews to authenticated;

drop policy if exists "public reads approved reviews" on public.reviews;
create policy "public reads approved reviews"
on public.reviews for select to anon, authenticated
using (approved or public.is_admin());

drop policy if exists "anyone submits unapproved review" on public.reviews;
create policy "anyone submits unapproved review"
on public.reviews for insert to anon, authenticated
with check (approved = false);

drop policy if exists "admins manage reviews" on public.reviews;
create policy "admins manage reviews"
on public.reviews for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins delete reviews" on public.reviews;
create policy "admins delete reviews"
on public.reviews for delete to authenticated
using (public.is_admin());

-- Contacts
grant insert on public.contacts to anon, authenticated;
grant select,update,delete on public.contacts to authenticated;

drop policy if exists "anyone submits contact" on public.contacts;
create policy "anyone submits contact"
on public.contacts for insert to anon, authenticated
with check (true);

drop policy if exists "admins read contacts" on public.contacts;
create policy "admins read contacts"
on public.contacts for select to authenticated
using (public.is_admin());

drop policy if exists "admins update contacts" on public.contacts;
create policy "admins update contacts"
on public.contacts for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins delete contacts" on public.contacts;
create policy "admins delete contacts"
on public.contacts for delete to authenticated
using (public.is_admin());

-- Subscribers: insertion through RPC only, admin reads.
grant select on public.subscribers to authenticated;

drop policy if exists "admins read subscribers" on public.subscribers;
create policy "admins read subscribers"
on public.subscribers for select to authenticated
using (public.is_admin());

-- Audit
grant select,insert on public.audit_log to authenticated;

drop policy if exists "admins read audit" on public.audit_log;
create policy "admins read audit"
on public.audit_log for select to authenticated
using (public.is_admin());

drop policy if exists "admins insert audit" on public.audit_log;
create policy "admins insert audit"
on public.audit_log for insert to authenticated
with check (public.is_admin());

-- ============================================================
-- Public sanitized views
-- These expose placeholders without leaking hidden lore.
-- ============================================================
create or replace view public.public_factions
with (security_invoker = false)
as
select
  id,
  case when revealed or (reveal_at is not null and reveal_at <= now()) then slug else format('classified-faction-%s',lpad((sort_order/10)::text,2,'0')) end as slug,
  rune, accent, sort_order, reveal_at,
  (revealed or (reveal_at is not null and reveal_at <= now())) as is_live,
  case when revealed or (reveal_at is not null and reveal_at <= now()) then name else 'CLASSIFIED' end as name,
  case when revealed or (reveal_at is not null and reveal_at <= now()) then tagline else 'The Veil has not lifted.' end as tagline,
  case when revealed or (reveal_at is not null and reveal_at <= now()) then lore else null end as lore,
  case when revealed or (reveal_at is not null and reveal_at <= now()) then doctrine else null end as doctrine,
  case when revealed or (reveal_at is not null and reveal_at <= now()) then image_url else null end as image_url
from public.factions;

create or replace view public.public_cards
with (security_invoker = false)
as
select
  c.id,
  case when c.revealed or (c.reveal_at is not null and c.reveal_at <= now()) then c.slug else format('classified-card-%s',lpad(c.card_number::text,3,'0')) end as slug,
  c.card_number, c.rarity, c.card_type, c.sort_order, c.reveal_at, c.faction_id,
  case when f.revealed or (f.reveal_at is not null and f.reveal_at <= now()) then f.slug else null end as faction_slug,
  case when f.revealed or (f.reveal_at is not null and f.reveal_at <= now()) then f.name else 'UNKNOWN' end as faction_name,
  (c.revealed or (c.reveal_at is not null and c.reveal_at <= now())) as is_live,
  case when c.revealed or (c.reveal_at is not null and c.reveal_at <= now()) then c.name else 'CLASSIFIED' end as name,
  case when c.revealed or (c.reveal_at is not null and c.reveal_at <= now()) then c.ability else null end as ability,
  case when c.revealed or (c.reveal_at is not null and c.reveal_at <= now()) then c.lore else null end as lore,
  case when c.revealed or (c.reveal_at is not null and c.reveal_at <= now()) then c.image_url else null end as image_url
from public.cards c
left join public.factions f on f.id = c.faction_id;

create or replace view public.public_whispers
with (security_invoker = false)
as
select id,published_at,title,body,classified,image_url,reveal_at
from public.whispers
where reveal_at is null or reveal_at <= now();

grant select on public.public_factions, public.public_cards, public.public_whispers to anon, authenticated;

-- ============================================================
-- Secure RPCs
-- ============================================================
create or replace function public.subscribe_email(input_email text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if input_email is null or position('@' in input_email) < 2 then
    raise exception 'Invalid email';
  end if;
  insert into public.subscribers(email,active)
  values (lower(trim(input_email)),true)
  on conflict(email) do update set active=true;
end;
$$;
grant execute on function public.subscribe_email(text) to anon,authenticated;

create or replace function public.unlock_vault_code(input_code text)
returns table(
  id bigint, code text, title text, teaser text, body text, image_url text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v public.vault_entries%rowtype;
begin
  if (select auth.uid()) is null then
    raise exception 'Sign in required';
  end if;

  select * into v
  from public.vault_entries
  where upper(access_code)=upper(trim(input_code))
  limit 1;

  if v.id is null then
    raise exception 'Invalid code';
  end if;

  insert into public.vault_unlocks(user_id,vault_entry_id)
  values ((select auth.uid()),v.id)
  on conflict do nothing;

  return query select v.id,v.code,v.title,v.teaser,v.body,v.image_url;
end;
$$;
grant execute on function public.unlock_vault_code(text) to authenticated;

create or replace function public.get_vault_entries()
returns table(
  id bigint, code text, title text, teaser text, body text,
  status text, reveal_at timestamptz, image_url text, unlocked boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select
    v.id,
    v.code,
    case when
      v.status='open' or (v.reveal_at is not null and v.reveal_at <= now())
      or public.is_admin()
      or exists(select 1 from public.vault_unlocks u where u.vault_entry_id=v.id and u.user_id=(select auth.uid()))
    then v.title else 'CLASSIFIED' end,
    v.teaser,
    case when
      v.status='open' or (v.reveal_at is not null and v.reveal_at <= now())
      or public.is_admin()
      or exists(select 1 from public.vault_unlocks u where u.vault_entry_id=v.id and u.user_id=(select auth.uid()))
    then v.body else null end,
    v.status,
    v.reveal_at,
    case when
      v.status='open' or (v.reveal_at is not null and v.reveal_at <= now())
      or public.is_admin()
      or exists(select 1 from public.vault_unlocks u where u.vault_entry_id=v.id and u.user_id=(select auth.uid()))
    then v.image_url else null end,
    (
      v.status='open' or (v.reveal_at is not null and v.reveal_at <= now())
      or public.is_admin()
      or exists(select 1 from public.vault_unlocks u where u.vault_entry_id=v.id and u.user_id=(select auth.uid()))
    )
  from public.vault_entries v
  order by v.id;
$$;
grant execute on function public.get_vault_entries() to anon,authenticated;

create or replace function public.admin_set_user_role(target_user uuid, new_role text, new_active boolean default true)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Admin required';
  end if;
  if new_role not in ('player','admin','owner') then
    raise exception 'Invalid role';
  end if;
  update public.profiles set role=new_role,active=new_active where id=target_user;
end;
$$;
grant execute on function public.admin_set_user_role(uuid,text,boolean) to authenticated;

-- ============================================================
-- Storage bucket for K&D media
-- ============================================================
insert into storage.buckets(id,name,public)
values ('kd-media','kd-media',true)
on conflict(id) do update set public=true;

drop policy if exists "public reads kd media" on storage.objects;
create policy "public reads kd media"
on storage.objects for select to public
using (bucket_id='kd-media');

drop policy if exists "admins upload kd media" on storage.objects;
create policy "admins upload kd media"
on storage.objects for insert to authenticated
with check (bucket_id='kd-media' and public.is_admin());

drop policy if exists "admins update kd media" on storage.objects;
create policy "admins update kd media"
on storage.objects for update to authenticated
using (bucket_id='kd-media' and public.is_admin())
with check (bucket_id='kd-media' and public.is_admin());

drop policy if exists "admins delete kd media" on storage.objects;
create policy "admins delete kd media"
on storage.objects for delete to authenticated
using (bucket_id='kd-media' and public.is_admin());

-- ============================================================
-- Seed current K&D public content.
-- Re-running is safe.
-- ============================================================
insert into public.factions(slug,name,rune,tagline,lore,doctrine,accent,revealed,sort_order)
values
('fehu','Fehu','ᚠ','Wealth has a blood price.','Fehu is the faction of wealth, possession, hunger, and the dangerous belief that everything has a price.','Acquire. Protect. Spend only when the blood price is worth paying.','#b58a42',true,10),
('godrin','Godrin','♛','The Empty Throne remembers.','Godrin endures beneath the shadow of the Empty Throne. Broken crowns and whispered oaths make power feel like a debt.','Authority is strongest when nobody agrees who truly holds it.','#7794bf',true,20),
('braided','Braided','∞','Fate is never a single thread.','Braided follows the Loom of Fate: crossing loyalties, hidden outcomes, and choices that tighten around everyone at the table.','Every action pulls another thread. Watch what moves when you pull.','#9b57cb',true,30)
on conflict(slug) do nothing;

do $$
declare i int;
begin
  for i in 4..13 loop
    insert into public.factions(slug,name,rune,tagline,lore,doctrine,accent,revealed,sort_order)
    values (
      format('classified-%s',lpad(i::text,2,'0')),
      format('CLASSIFIED %s',lpad(i::text,2,'0')),
      '◇','The Veil has not lifted.','This faction remains sealed behind the Veil.',
      'Doctrine unavailable.','#635a70',false,i*10
    )
    on conflict(slug) do nothing;
  end loop;
end $$;

insert into public.cards(slug,card_number,name,faction_id,rarity,card_type,ability,lore,image_url,revealed,sort_order)
select 'fehu-blood-price',1,'Blood Price',f.id,'Rare','Action',
'Trade certainty for leverage. The table sees the cost; only you know whether it was worth paying.',
'Coins remember every hand that held them.','assets/img/card-back.svg',true,10
from public.factions f where f.slug='fehu'
on conflict(slug) do nothing;

insert into public.cards(slug,card_number,name,faction_id,rarity,card_type,ability,lore,image_url,revealed,sort_order)
select 'godrin-empty-throne',2,'Empty Throne',f.id,'Mythic','Relic',
'Authority changes the room even when nobody sits the throne.',
'A vacant seat can rule more effectively than a king.','assets/img/card-back.svg',true,20
from public.factions f where f.slug='godrin'
on conflict(slug) do nothing;

insert into public.cards(slug,card_number,name,faction_id,rarity,card_type,ability,lore,image_url,revealed,sort_order)
select 'braided-loose-thread',3,'Loose Thread',f.id,'Uncommon','Kloak',
'Leave one truth visible so the lie beside it becomes believable.',
'Pull gently. Some knots tighten when challenged.','assets/img/card-back.svg',true,30
from public.factions f where f.slug='braided'
on conflict(slug) do nothing;

do $$
declare
  i int;
  rarities text[] := array['Common','Uncommon','Rare','Mythic','Gold'];
  ctypes text[] := array['Action','Kloak','Faction','Reaction','Relic'];
begin
  for i in 4..24 loop
    insert into public.cards(slug,card_number,name,rarity,card_type,ability,lore,image_url,revealed,sort_order)
    values (
      format('classified-card-%s',lpad(i::text,3,'0')),i,
      format('CLASSIFIED #%s',lpad(i::text,3,'0')),
      rarities[((i-1)%5)+1],ctypes[((i-1)%5)+1],
      'Ability redacted.','Archive sealed.','assets/img/card-back.svg',false,i*10
    )
    on conflict(slug) do nothing;
  end loop;
end $$;

insert into public.whispers(published_at,title,body,classified)
values
('2026-08-26','THE VEIL LIFTS','A signal has been received. Thirteen factions are moving, but only a few have chosen to reveal themselves.',false),
('2026-08-29','ARCHIVE FRAGMENT 001','Three sigils have surfaced. The rest remain sealed. Do not mistake silence for absence.',true)
on conflict(title,published_at) do nothing;

insert into public.vault_entries(code,title,teaser,body,status,access_code)
values
('KD-001','THE FIRST SIGNAL','A transmission recovered from beyond the Veil.','The first archive is open. Every faction leaves a trace. Very few leave it willingly.','open',null),
('KD-013','THE THIRTEENTH NAME','Identity redacted by order of the Archive.','You were not supposed to find this file.','locked','THIRTEEN'),
('KD-404','BLACK FILE','Clearance insufficient.','The Archive remembers failed attempts.','locked',null)
on conflict(code) do nothing;

insert into public.site_settings(key,value) values
('hero_eyebrow','KLOAK & DAGGURRS PRESENTS'),
('hero_title','KLANDESTINE'),
('hero_line_1','Some secrets are worth keeping.'),
('hero_line_2','Others are worth killing for.')
on conflict(key) do nothing;
