-- ============================================================
-- CARDS DATABASE SCHEMA - KLOAK & DAGGURRS
-- ============================================================

-- Drop existing cards table if it exists with old structure
drop table if exists public.cards cascade;

-- Create cards table with new structure
create table public.cards (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  
  -- Basic Info
  name text not null,
  card_number text not null,
  set_name text not null,
  faction_slug text not null references public.factions(slug) on delete cascade,
  
  -- Type & Rarity
  type text not null check (type in ('Vigor', 'Creature', 'Accoutrements', 'Runes', 'Primordial Being')),
  rarity text check (rarity in ('Thrall', 'Skilled', 'Karls', 'Jarl', 'Konugr')),
  
  -- Vigor Info
  vigor_type text,
  vigor_cost integer,
  
  -- Creature/Primordial Stats
  class_name text,
  ap integer,
  dp integer,
  mana_card_cost integer,
  
  -- Strength/Weakness
  strength_vigor text,
  weakness_vigor text,
  
  -- Attacks (JSON array)
  attacks jsonb,
  
  -- Equipment/Runes specific
  equipment_type text,
  attack_name text,
  attack_description text,
  
  -- Reveal Status
  revealed boolean not null default false,
  reveal_at timestamptz,
  
  -- Image Path
  image_url text,
  
  -- Sorting
  sort_order integer default 0
);

-- Enable RLS
alter table public.cards enable row level security;

-- Grant permissions
grant select on public.cards to anon, authenticated;
grant select,insert,update,delete on public.cards to authenticated;

-- Public read policy
drop policy if exists "public read cards" on public.cards;
create policy "public read cards"
on public.cards for select to anon, authenticated
using (true);

-- Admin manage policy
drop policy if exists "admins manage cards" on public.cards;
create policy "admins manage cards"
on public.cards for all to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Create indexes for performance
create index idx_cards_faction on public.cards(faction_slug);
create index idx_cards_type on public.cards(type);
create index idx_cards_rarity on public.cards(rarity);
create index idx_cards_vigor on public.cards(vigor_type);
create index idx_cards_name on public.cards(name);