-- ============================================================
-- Deck Redemption System for Klandestine
-- Similar to Pokémon Live code redemption
-- ============================================================

-- Table for pre-built decks (physical decks that can be redeemed)
create table if not exists public.decks (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  description text not null default '',
  faction_slug text, -- optional: primary faction of the deck
  total_cards integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  image_url text
);

-- Table for deck redemption codes (like Pokémon code cards)
create table if not exists public.deck_codes (
  id bigint generated by default as identity primary key,
  code text unique not null, -- the physical code printed on cards
  deck_id bigint not null references public.decks(id) on delete cascade,
  is_redeemed boolean not null default false,
  redeemed_by uuid references auth.users(id) on delete set null,
  redeemed_at timestamptz,
  created_at timestamptz not null default now(),
  expires_at timestamptz -- optional: codes can expire
);

-- Table for deck composition (which cards are in each deck)
create table if not exists public.deck_cards (
  deck_id bigint not null references public.decks(id) on delete cascade,
  card_id bigint not null references public.cards(id) on delete cascade,
  quantity integer not null default 1 check (quantity between 1 and 99),
  primary key(deck_id, card_id)
);

-- Table for user deck ownership (which decks they've redeemed)
create table if not exists public.user_decks (
  user_id uuid not null references auth.users(id) on delete cascade,
  deck_id bigint not null references public.decks(id) on delete cascade,
  redeemed_at timestamptz not null default now(),
  redemption_code text not null, -- store which code was used
  primary key(user_id, deck_id)
);

-- Enable RLS
alter table public.decks enable row level security;
alter table public.deck_codes enable row level security;
alter table public.deck_cards enable row level security;
alter table public.user_decks enable row level security;

-- Policies for decks (public can read active decks)
grant select on public.decks to anon, authenticated;
grant select,insert,update,delete on public.decks to authenticated;

drop policy if exists "public read active decks" on public.decks;
create policy "public read active decks"
on public.decks for select to anon, authenticated
using (is_active or public.is_admin());

drop policy if exists "admins manage decks" on public.decks;
create policy "admins manage decks"
on public.decks for all to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Policies for deck_cards (public can read, admins manage)
grant select on public.deck_cards to anon, authenticated;
grant select,insert,update,delete on public.deck_cards to authenticated;

drop policy if exists "public read deck cards" on public.deck_cards;
create policy "public read deck cards"
on public.deck_cards for select to anon, authenticated
using (exists (
  select 1 from public.decks d 
  where d.id = deck_cards.deck_id and (d.is_active or public.is_admin())
));

drop policy if exists "admins manage deck cards" on public.deck_cards;
create policy "admins manage deck cards"
on public.deck_cards for all to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Policies for deck_codes (users can redeem, admins manage)
grant select on public.deck_codes to authenticated;
grant select,insert,update on public.deck_codes to authenticated;

drop policy if exists "users can check codes" on public.deck_codes;
create policy "users can check codes"
on public.deck_codes for select to authenticated
using (true); -- users can check if a code exists

drop policy if exists "admins manage deck codes" on public.deck_codes;
create policy "admins manage deck codes"
on public.deck_codes for all to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Policies for user_decks (users read own, admins read all)
grant select on public.user_decks to authenticated;
grant select,insert on public.user_decks to authenticated;

drop policy if exists "users read own decks" on public.user_decks;
create policy "users read own decks"
on public.user_decks for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "users redeem decks" on public.user_decks;
create policy "users redeem decks"
on public.user_decks for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "admins read all user decks" on public.user_decks;
create policy "admins read all user decks"
on public.user_decks for select to authenticated
using (public.is_admin());

-- ============================================================
-- Function to redeem a deck code
-- ============================================================
create or replace function public.redeem_deck_code(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deck_code deck_codes%rowtype;
  v_user_id uuid;
  v_result jsonb;
begin
  -- Get current user
  v_user_id := auth.uid();
  if v_user_id is null then
    return jsonb_build_object(
      'success', false,
      'error', 'Authentication required'
    );
  end if;

  -- Find the code
  select * into v_deck_code
  from public.deck_codes
  where code = upper(trim(p_code))
  and (expires_at is null or expires_at > now());

  if not found then
    return jsonb_build_object(
      'success', false,
      'error', 'Invalid or expired code'
    );
  end if;

  -- Check if already redeemed
  if v_deck_code.is_redeemed then
    return jsonb_build_object(
      'success', false,
      'error', 'Code already redeemed'
    );
  end if;

  -- Check if user already owns this deck
  if exists (
    select 1 from public.user_decks
    where user_id = v_user_id and deck_id = v_deck_code.deck_id
  ) then
    return jsonb_build_object(
      'success', false,
      'error', 'You already own this deck'
    );
  end if;

  -- Start transaction to redeem
  begin
    -- Mark code as redeemed
    update public.deck_codes
    set is_redeemed = true,
        redeemed_by = v_user_id,
        redeemed_at = now()
    where id = v_deck_code.id;

    -- Add deck to user's collection
    insert into public.user_decks(user_id, deck_id, redemption_code)
    values (v_user_id, v_deck_code.deck_id, v_deck_code.code);

    -- Add all cards from deck to user's collection
    insert into public.collections(user_id, card_id, quantity)
    select v_user_id, dc.card_id, dc.quantity
    from public.deck_cards dc
    where dc.deck_id = v_deck_code.deck_id
    on conflict(user_id, card_id) do update set
      quantity = collections.quantity + excluded.quantity,
      updated_at = now();

    -- Get deck info for response
    select jsonb_build_object(
      'success', true,
      'deck_id', v_deck_code.deck_id,
      'deck_name', d.name,
      'cards_added', (select count(*) from public.deck_cards where deck_id = v_deck_code.deck_id)
    ) into v_result
    from public.decks d
    where d.id = v_deck_code.deck_id;

    return v_result;

  exception when others then
    return jsonb_build_object(
      'success', false,
      'error', 'Redemption failed: ' || sqlerrm
    );
  end;
end;
$$;

grant execute on function public.redeem_deck_code(text) to authenticated;

-- ============================================================
-- Function to get user's redeemed decks
-- ============================================================
create or replace function public.get_user_decks()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_result jsonb;
begin
  select jsonb_agg(
    jsonb_build_object(
      'deck_id', ud.deck_id,
      'deck_name', d.name,
      'deck_slug', d.slug,
      'redeemed_at', ud.redeemed_at,
      'redemption_code', ud.redemption_code,
      'total_cards', d.total_cards,
      'image_url', d.image_url
    )
  ) into v_result
  from public.user_decks ud
  join public.decks d on d.id = ud.deck_id
  where ud.user_id = auth.uid();

  return coalesce(v_result, '[]'::jsonb);
end;
$$;

grant execute on function public.get_user_decks() to authenticated;

-- ============================================================
-- Verification query
-- ============================================================
-- Run this to verify installation:
-- select 'decks' as table_name, count(*) as record_count from public.decks
-- union all select 'deck_codes', count(*) from public.deck_codes
-- union all select 'deck_cards', count(*) from public.deck_cards
-- union all select 'user_decks', count(*) from public.user_decks;